executor: KubernetesExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/techiescamp/airflow-setup.git
    branch: main
    subPath: "dags"
    period: 60s
    credentialsSecret: git-credentials